### ISSUE TITLE
Please check nonascii characters

### ISSUE THREAD

**Issue by zarquon42b** [zarquon42b/literature#1]
@Luuuuzi : please check for non-ascii characters before committing them, it is very cumbersome to do this afterwards (doing that right now)

**Comment by Luuuuzi** [comment]
sorry,mache ich eigentlich...bitte um ein Beispiel,wo ich es vergessen 
habe !

Danke und sorry nochmal,

alex

**Comment by zarquon42b** [comment]
Macht nix,
das waren die Änderungen: https://github.com/zarquon42b/literature/commit/66b2f069e1ee83f1d457901f7d367ba18efc1f48
